---
- name: Configure roles on web server
  hosts: all
  become: true
  vars:
    web_document_root: "/var/www/teamdigitale.governo.it"
    # NGINX role, see https://galaxy.ansible.com/geerlingguy/nginx/
    nginx_remove_default_vhost: true
    nginx_sendfile: "on"
    nginx_tcp_nopush: "on"
    nginx_tcp_nodelay: "on"
    nginx_server_tokens: "off"
    nginx_ppa_use: true
    nginx_ppa_version: "stable"
    nginx_extra_http_options: |
      gzip on;
      gzip_disable "msie6";
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;
      gzip_min_length 256;
      gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/bmp
        image/svg+xml
        image/x-icon
        text/cache-manifest
        text/css
        text/plain
        text/vcard
        text/vnd.rim.location.xloc
        text/vtt
        text/x-component
        text/x-cross-domain-policy;
    nginx_vhosts:
      - listen: "443 ssl default_server"
        server_name: "teamdigitale.governo.it"
        root: "{{ web_document_root }}"
        index: "index.html"
        extra_parameters: |
          listen [::]:443 ssl default_server;
          ssl_certificate /etc/ssl/private/teamdigitale_governo_it.crt;
          ssl_certificate_key /etc/ssl/private/teamdigitale_governo_it.key;
          ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
          ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
          expires $expires;
          add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";
          # nginx redirect italian and english job pages
          location ~ ^/it/jobs/1-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/cto.htm;
          }
          location ~ ^/it/jobs/2-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/applied-data-scientist.htm;
          }
          location ~ ^/it/jobs/3-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/cybersecurity.htm;
          }
          location ~ ^/it/jobs/4-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/sviluppo-mobile-app.htm;
          }
          location ~ ^/it/jobs/5-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/pagamenti-digitali.htm;
          }
          location ~ ^/it/jobs/6-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/prodotto-ux-ui.htm;
          }
          location ~ ^/it/jobs/7-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/affari-regolamentari.htm;
          }
          location ~ ^/it/jobs/8-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/metrics-analytics.htm;
          }
          location ~ ^/it/jobs/9-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/relazioni-sviluppatori.htm;
          }
          location ~ ^/it/jobs/10-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/content-designer.htm;
          }
          location ~ ^/it/jobs/11-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/comunicazione-pr.htm;
          }
          location ~ ^/it/jobs/12-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/collaborazioni-internazionali.htm;
          }
          location ~ ^/it/jobs/13-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/big-data-architect.htm;
          }
          location ~ ^/it/jobs/14-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/assistente-tecnico.htm;
          }
          location ~ ^/it/jobs/29-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/sviluppatori-software.htm;
          }
          location ~ ^/it/jobs/30-detail.htm {
            return 301 https://teamdigitale.governo.it/it/jobpositions/open-source-project-leader.htm;
          }
          location ~ ^/en/jobs/17-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/big-data-architect.htm;
          }
          location ~ ^/en/jobs/18-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/cybersecurity.htm;
          }
          location ~ ^/en/jobs/19-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/mobile-app-development.htm;
          }
          location ~ ^/en/jobs/20-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/digital-payments.htm;
          }
          location ~ ^/en/jobs/21-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/product-ux-ui.htm;
          }
          location ~ ^/en/jobs/22-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/content-design.htm;
          }
          location ~ ^/en/jobs/23-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/metrics-analytics.htm;
          }
          location ~ ^/en/jobs/27-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/international-collaborations.htm;
          }
          location ~ ^/en/jobs/31-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/software-developers.htm;
          }
          location ~ ^/en/jobs/32-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/technical-project-manager.htm;
          }
          location ~ ^/en/jobs/15-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/cto.htm;
          }
          location ~ ^/en/jobs/16-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/applied-data-scientist.htm;
          }
          location ~ ^/en/jobs/24-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/developer-relations.htm;
          }
          location ~ ^/en/jobs/25-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/communication-pr.htm;
          }
          location ~ ^/en/jobs/28-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/technical-assistant.htm;
          }
          location ~ ^/en/jobs/26-detail.htm {
            return 301 https://teamdigitale.governo.it/en/jobpositions/regulatory-affairs.htm;
          }
          # nginx gzip_static does not add Vary header for fonts.
          location ~* \.(?:eot|ttf|svg)$ {
            expires max;
            add_header Vary Accept-Encoding;
            add_header Cache-Control public;
            access_log off;
          }
          # woff fonts should not be zipped.
          location ~* \.(?:woff|woff2)$ {
            expires max;
            add_header Cache-Control public;
            access_log off;
          }
          include /etc/nginx/conf.d/security_headers.conf;
      - listen: "80 default_server"
        server_name: "teamdigitale.governo.it"
        extra_parameters: |
          listen [::]:80 default_server;
          return 301 https://$server_name$request_uri;
          include /etc/nginx/conf.d/security_headers.conf;

  tasks:
    - name: "NGINX cache expire config map"
      copy:
        content: |
          # Expires map
          map $sent_http_content_type $expires {
              default                    off;
              text/html                  epoch;
              text/css                   max;
              application/javascript     max;
              ~image/                    max;
              ~fonts/                    max;
          }
        dest: /etc/nginx/conf.d/expires_map.conf

    - name: "NGINX extra headers"
      copy:
        content: |
          # Extra security headers
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;
          add_header X-XSS-Protection "1; mode=block";
          add_header Referrer-Policy "no-referrer";
        dest: "/etc/nginx/conf.d/security_headers.conf"

    - name: "Document root directory"
      file:
        path: "{{ web_document_root }}"
        owner: www-data
        group: www-data
        state: directory
        mode: 0775

  roles:
    - { role: geerlingguy.nginx }
